import AreaComponent from './components/charts/area';
import BarComponent from './components/charts/bar';
import GaugeComponent from './components/charts/gauge';
import HeatmapComponent from './components/charts/heatmap';
import LineComponent from './components/charts/line';
import MultiGaugeComponent from './components/charts/multi-gauge';
import PieComponent from './components/charts/pie';
import StackedGaugeComponent from './components/charts/stacked-gauge';
import { AcicAggregation, AcicEvent } from './lib/props';

export default function TestDashboard() {
  return (
    <div className="w-full grid grid-cols-3 gap-2">
      <AreaComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="natural"
        widgetId=""
      />
      <AreaComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="linear"
        widgetId=""
      />
      <AreaComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="step"
        widgetId=""
      />
      <LineComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="natural"
        widgetId=""
      />
      <LineComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="linear"
        widgetId=""
      />
      <LineComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="step"
        widgetId=""
      />
      <AreaComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="natural"
        groupBy="direction"
        stackOffset="none"
        widgetId=""
      />
      <AreaComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="natural"
        groupBy="direction"
        stackOffset="expand"
        widgetId=""
      />
      <AreaComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="natural"
        groupBy="direction"
        stackOffset="wiggle"
        widgetId=""
      />
      <LineComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="natural"
        groupBy="direction"
        widgetId=""
      />
      <LineComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="linear"
        groupBy="direction"
        widgetId=""
      />
      <LineComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="step"
        groupBy="direction"
        widgetId=""
      />
      <BarComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneWeek}
        aggregation={AcicAggregation.OneDay}
        layout="horizontal"
        widgetId=""
      />
      <BarComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneWeek}
        aggregation={AcicAggregation.OneDay}
        layout="horizontal stacked"
        groupBy="direction"
        widgetId=""
      />
      <BarComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneWeek}
        aggregation={AcicAggregation.OneDay}
        layout="horizontal"
        groupBy="direction"
        widgetId=""
      />
      <BarComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneWeek}
        aggregation={AcicAggregation.OneDay}
        layout="vertical"
        widgetId=""
      />
      <BarComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneWeek}
        aggregation={AcicAggregation.OneDay}
        layout="vertical stacked"
        groupBy="direction"
        widgetId=""
      />
      <BarComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneWeek}
        aggregation={AcicAggregation.OneDay}
        layout="vertical"
        groupBy="direction"
        widgetId=""
      />
      <PieComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="donut"
        gap={0}
        widgetId=""
      />
      <PieComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="pie"
        gap={1}
        widgetId=""
      />
      <PieComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="donut"
        gap={4}
        widgetId=""
      />
      <PieComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="halfdonut"
        gap={0}
        widgetId=""
      />
      <PieComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="halfpie"
        gap={1}
        widgetId=""
      />
      <PieComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="halfdonut"
        gap={4}
        widgetId=""
      />
      <GaugeComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="half"
        widgetId=""
      />
      <div className="col-span-1"> </div>
      <GaugeComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        layout="full"
        widgetId=""
      />
      <MultiGaugeComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="full"
        widgetId=""
      />
      <MultiGaugeComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="half"
        widgetId=""
      />
      <StackedGaugeComponent
        table={AcicEvent.AcicCounting}
        duration={AcicAggregation.OneDay}
        aggregation={AcicAggregation.OneHour}
        groupBy="direction"
        layout="half"
        widgetId=""
      />
      <div className="col-span-3">
        <HeatmapComponent
          table={AcicEvent.AcicAllInOneEvent}
          aggregation={AcicAggregation.OneHour}
          duration={AcicAggregation.OneWeek}
          layout="horizontal"
          widgetId=""
        />
      </div>
      <div className="col-span-3">
        <HeatmapComponent
          table={AcicEvent.AcicAllInOneEvent}
          aggregation={AcicAggregation.OneHour}
          duration={AcicAggregation.OneWeek}
          layout="vertical"
          widgetId=""
        />
      </div>
    </div>
  );
}
