name: Test Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run builds
        working-directory: ./frontend
        run: npm run build

      - name: Run tests with coverage
        working-directory: ./frontend
        run: npm run coverage

      - name: Check coverage threshold
        working-directory: ./frontend
        run: |
          THRESHOLD=55

          # Get the lines coverage percentage from coverage-summary.json
          COVERAGE_TOTAL=$(cat coverage/coverage-summary.json | jq -r '.total.lines.pct')

          echo "Coverage: $COVERAGE_TOTAL%"
          echo "Threshold: $THRESHOLD%"

          if (( $(echo "$COVERAGE_TOTAL < $THRESHOLD" | bc -l) )); then
            echo "::error::Coverage is below threshold! ($COVERAGE_TOTAL% < $THRESHOLD%)"
            exit 1
          else
            echo "Coverage threshold met! ($COVERAGE_TOTAL% >= $THRESHOLD%)"
          fi
